server {
    listen $PORT;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Cache static data files
    location ~* \.(json|topojson|csv)$ {
        add_header Cache-Control "public, max-age=3600";
    }

    # Gzip
    gzip on;
    gzip_types application/json application/geo+json text/html text/css text/csv;
}
